version: '3'
services:
  # The grafana container
  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    # Mounting configuration file and persistent storage
    volumes:
      - ./data/grafanaData:/var/lib/grafana
      - ./configuration/grafana.ini:/etc/grafana/grafana.ini
    ports:
      - 3000:3000
    networks:
       - main-network
    depends_on:
      - influxdb
    restart: unless-stopped

  # InfluxDB database container
  influxdb:
    container_name: influxdb
    image: influxdb:latest
    # Mount persistent storage
    volumes:
       - ./data/influxdbData:/var/lib/influxdb
    ports:
       - 8086:8086
    networks:
       - main-network
    
    # Environment variables to create users and default database
    environment:
      - INFLUXDB_DB=maindb
      - INFLUXDB_USER=grafana
      - INFLUXDB_USER_PASSWORD=password
      - INFLUXDB_ADMIN_ENABLED=true
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=password
    restart: unless-stopped
  
  # NGINX Reverse proxy container
  nginx:
    container_name: nginx
    image: nginx:latest
    # Mounting the configuration file and static webpage
    volumes:
       - ./configuration/nginx.conf:/etc/nginx/nginx.conf:ro
       - ./web/:/usr/share/nginx/html/:ro
    ports:
       - 80:80
    networks:
       - main-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
       - grafana
       - influxdb
    restart: unless-stopped

  portainer:
      container_name: portainer
      image: portainer/portainer:latest
      volumes:
         - /var/run/docker.sock:/var/run/docker.sock
         - ./data/portainerData:/data
      ports:
        - 9000:9000
      networks:
       - main-network
      depends_on:
        - nginx
      restart: unless-stopped

# The shared container network - Named for consistency
networks: 
  main-network:
    name: main-network
    driver: bridge